### ISSUE TITLE
favicon does not display in Firefox

### ISSUE THREAD

**Issue by fauxmight** [AkazieIT/grav-theme-akazie-wood#9]
In Chromium, the default or custom-chosen favicon displays correctly in a browser tab.
In Firefox, I cannot get either the default or a custom-chosen favicon to display.

Have tried 16x16, 32x32, 192x192 and 512x512 size favicon files, all with the same result described above.

**Comment by grimnebluna** [comment]
I will check & fix this in the next release. Gonna let u know when it's fixed

**Comment by grimnebluna** [comment]
the bug will be fixed in the next release 0.9.948 (coming during the next 1-2 weeks). for now you can place a favicon.ico in your root folder as a workaround.

**Comment by fauxmight** [comment]
@grimnebluna Many thanks.
Your work and your theme are appreciated

**Comment by grimnebluna** [comment]
thanks!

the update has been pushed and will be available shortly. but be careful. since the last grav releae the custom folder inside akazie-wood gets overwritten with every update. so until we have a solution for that you need to back up your custom folder before the update and then copy it back after the update.

See ticket #10
